"""Developer-side tool: build the "easy start" save shipped as an optional
convenience in the release bundle (see tools/release/starter_save/).

## Why this isn't just a patched copy of STARTUP.GAM

The first version of this script built the save from the pristine
STARTUP.GAM ("New Game" template). That crashed on load ("cannot load gi
block" / Null pointer assignment, SRC/R3D/SCENE/PROXIM.C: proximity_table_load)
when picked from the in-game Load Game menu. `gmain_start_dispatch()`
(SRC/GAME/GMAIN.C) routes New Game (mode 2, reads STARTUP.GAM) and Load Game
(mode 3, reads a GAMES\\<slot>.G0N\\SAVE0N.GAM) through the exact same
`savegame_read()`, so the two paths *look* equivalent -- but empirically,
STARTUP.GAM is only ever exercised through the New Game path in the shipped
game, and evidently isn't in a state the generic Load Game path can safely
resume from (most likely something in the Actor pool /
shared_inventory/ground_pile region that New Game's own follow-up setup
fixes up but Load Game assumes is already valid).

Rather than fully reverse-engineer that gap, this instead starts from one of
this project's own already-proven-loadable QA saves -- real chapter-1
gameplay, generated by the project's own testing, already referenced
elsewhere in this project's history as a working Load Game save (see
tools/release/starter_save_base/) -- and only patches the single field this
save is meant to differ by: starting gold. That save's character names are
already Chinese-translated (all of this project's archived QA saves are), so
no name patch is needed here.

## How the nParty_gold byte offset was determined

`SRC/GAME/STATE/SAVEGAME.C: savegame_write/read` write a 100-byte header
(90-byte g_abSaveFileHeader + nChapter + 3 bookmark fields + a 2-byte version
that must read back as 0x16), followed by a raw copy of TEMP.GAM, which is
GameState (SRC/GAME/GMAIN.H) serialized starting at TEMP.GAM offset 0. Since
`nChapter` (u16) is the first GameState field and `nParty_gold` (i32) is the
second with no compiler padding between them on this 16-bit target, that
places nParty_gold at absolute file offset 100 + 2 = 102, 4 bytes, signed
little-endian. Cross-validated three independent ways: (a) the header's own
duplicate copy of nChapter at offset 0x5a matches the GameState-blob copy at
offset 100 in every sample file; (b) the version field at offset 0x62 reads
back exactly 0x16 as SAVEGAME.C expects; (c) the value at offset 102 is 0 in
untouched STARTUP.GAM and increases plausibly with playthrough progress
across all 40 of this project's own archived QA saves under
dist/test_v100_zh/GAMES/.

Usage:
    python tools/release/build_starter_save.py
"""

from __future__ import annotations

import struct
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

BASE_SAVE_PATH = REPO_ROOT / "tools" / "release" / "starter_save_base" / "verified_chapter1_save.GAM"
OUT_PATH = REPO_ROOT / "tools" / "release" / "starter_save" / "GAMES" / "NewGamePlus.G01" / "SAVE00.GAM"

GOLD_OFFSET = 102
GOLD_SIZE = 4
STARTER_GOLD = 1000


def build(base_save_path: Path, out_path: Path, starter_gold: int) -> None:
    data = bytearray(base_save_path.read_bytes())

    (original_gold,) = struct.unpack_from("<l", data, GOLD_OFFSET)
    if not (0 <= original_gold < starter_gold):
        raise SystemExit(
            f"{base_save_path} 的起始金幣是 {original_gold}，不在預期的「比 {starter_gold} 少」範圍內，"
            "先確認這還是原本挑選的那份基準存檔、offset 假設沒有被破壞。"
        )
    struct.pack_into("<l", data, GOLD_OFFSET, starter_gold)

    original = base_save_path.read_bytes()
    diff_offsets = [i for i in range(len(original)) if original[i] != data[i]]
    unexpected = [i for i in diff_offsets if not (GOLD_OFFSET <= i < GOLD_OFFSET + GOLD_SIZE)]
    if unexpected:
        raise SystemExit(f"拒絕寫出：除了金幣欄位還有其他 byte 被改到了：{unexpected[:10]}...")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(bytes(data))

    print(f"OK: {out_path} ({len(data)} bytes)")
    print(f"    起始金幣：{original_gold} -> {starter_gold}")


def main() -> None:
    build(BASE_SAVE_PATH, OUT_PATH, STARTER_GOLD)


if __name__ == "__main__":
    main()
